# Generated by Django 5.2.13 on 2026-05-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contact',
            new_name='content',
        ),
    ]
