# Generated by Django 5.2.13 on 2026-05-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/blog/default.jpg', upload_to='blog'),
        ),
    ]
